Uniswap/v4-periphery

contracts/hooks/examples/TWAMM.sol, test/TWAMM.t.sol
- fix missed accounting in `claimTokens`
- remove unused `TWAMM.OrderParams` struct, which seems duplicated with `ITWAMM.OrderKey`
=> Fix `TWAMM.claimTokens`

contracts/base/Multicall.sol, contracts/base/PeripheryPayments.sol, contracts/base/PeripheryValidation.sol, contracts/base/SelfPermit.sol, contracts/interfaces/IMulticall.sol, contracts/interfaces/IPeripheryPayments.sol, contracts/interfaces/ISelfPermit.sol, contracts/interfaces/external/IERC1271.sol, contracts/interfaces/external/IERC20PermitAllowed.sol
This PR adds base contracts and interfaces that are used in PositionManagerV4 [here](https://github.com/Uniswap/v4-periphery/pull/76). But these are mostly copied from v3-periphery with a few changes (ill document as comments).
=> Add base contracts and interfaces used in PositionManager

test/StateViewTest.t.sol, test/position-managers/Execute.t.sol, test/position-managers/NativeToken.t.sol, test/position-managers/PositionManager.t.sol
some chore cleanup now that core has a helper function for calculating positionId
=> [chore]: use positionId helper instead of manually hashing

src/V4Router.sol, src/libraries/SafeCast.sol
this breaks universal router to have them with the same name in core and periphery lol
=> rename SafeCast lib

src/libraries/CurrencyDeltas.sol, test/libraries/CurrencyDeltas.t.sol, test/mocks/MockCurrencyDeltaReader.sol
Also known as 2 birds 1 stone!!!
A library which returns two currency deltas in a single exttload call
=> Multi CurrencyDeltas Library

src/PositionManager.sol
Which issue does this pull request resolve?
This PR makes the `PositionManager.transferFrom` method `virtual` so that integrators
who are extending `PositionManger` can override its functionality more easily.
=> Allow integrators to override `PositionManager.transferFrom`

src/base/Notifier.sol
`unsubscribe()` does not follow check-effect-interaction pattern
* This would lead to obscure cases where integrators (called by subscribers) may mistaken that a tokenId has a subscriber
`delete subscriber[tokenId]` before calling `subscriber.notifyUnsubscribe()`
=> chore: OZ-L04 adherence to CEI in unsubscribe

src/base/PoolInitializer.sol, test/position-managers/PositionManager.multicall.t.sol
SB-L73: missing payable
**NOTE:** the spearbit issue states we are missing `payable` on the ERC721 methods. However, we cannot override Solmate's functions and change from `nonpayable` to `payable`
* Added `payable` to `initializePool` 
* unit test `multicall(initializePool, mint)`
=> SB-L73: payable initializePool

src/base/Permit2Forwarder.sol, test/position-managers/PositionManager.multicall.t.sol
We believe the `Wrap__` notation should only be reserved for "unknown"/"variable" external calls (subscribers, hooks, tokens, etc). So we are removing it from permit2 error handling, to be consistent with external calls to PoolManager
Removed `Wrap__` notation from permit2 error handling
=> Remove Wrap__ notation from permit2 revert reason

src/libraries/SVG.sol
Pashov M-01 https://github.com/PashovAuditGroup/Uniswap_October_MERGED/issues/12
Hook address is not correctly represented in the SVG
make sure the last 3 characters of the hook address are displayed
=> Pashov M-01 fix hook address

src/PositionManager.sol, src/base/PoolInitializer_v4.sol, src/interfaces/IPoolInitializer_v4.sol, src/interfaces/IPositionManager.sol, test/position-managers/PositionManager.gas.t.sol, test/position-managers/PositionManager.multicall.t.sol
typechain error in universal router
`Cannot redefine property: IPoolInitializer__factory`
rename PoolInitializer in v4 so it's not the same as v3
=> change name for UR

src/interfaces/IEIP712_v4.sol, src/interfaces/IERC721Permit_v4.sol, src/interfaces/IImmutableState.sol, src/interfaces/IMulticall_v4.sol, src/interfaces/INotifier.sol, src/interfaces/IPoolInitializer_v4.sol, src/interfaces/IPositionDescriptor.sol, src/interfaces/IStateView.sol, src/interfaces/ISubscriber.sol, src/interfaces/IUniswapV4DeployerCompetition.sol, src/interfaces/IUnorderedNonce.sol, src/interfaces/IV4Quoter.sol, src/interfaces/IV4Router.sol, src/interfaces/external/IWETH9.sol, src/lens/StateView.sol, src/lens/V4Quoter.sol
Which issue does this pull request resolve?
=> make natspec consistent

src/lens/V4Quoter.sol
The quoter does not return the sqrt price after a quote. Remove conflicting comment
=> doc: quoter does not return sqrt price

src/base/ImmutableState.sol, src/base/SafeCallback.sol, src/utils/BaseHook.sol, test/SafeCallback.t.sol
Which issue does this pull request resolve?
=> Move BaseHook to new utils directory

README.md
Following this PR: https://github.com/Uniswap/v4-periphery/pull/438 the `BaseHook.sol` file is in a new folder, the README.md became obsolete. This PR fixes it.
Fix import of `BaseHook.sol` in README.md
=> Update BaseHook.sol import path in README

snapshots/QuoterTest.json, src/base/BaseActionsRouter.sol, src/interfaces/IMsgSender.sol, src/interfaces/IV4Quoter.sol, src/lens/V4Quoter.sol, test/V4Quoter.t.sol, test/mocks/MockMsgSenderHook.sol
There's a growing subset of hooks which read the "wallet" of the swapper (or position creator). These hooks normally use the `msgSender()` view function exposed by Universal Router and PosM, and can facilitate transactions without failure
However, `msgSender()` was not available on V4Quoter, causing reverts/failures when using the quoter against a hook'd pool reading `msgSender()`
Add `msgSender() external view returns (address)` to V4Quoter.sol via transient storage
Add `IMsgSender` and added inheritance to IV4Quoter, BaseActionsRouter
=> Add `msgSender()` to V4Quoter

.github/workflows/semgrep.yml, src/base/hooks/BaseTokenWrapperHook.sol, src/hooks/WETHHook.sol, src/hooks/WstETHHook.sol, src/utils/BaseHook.sol
L01 - fix basehook docstring
L02 - fix floating pragmas
N01 - remove unused named returns
Which issue does this pull request resolve?
=> fix: OpenZeppelin token wrapper audit

src/hooks/permissionedPools/BaseAllowListChecker.sol, src/hooks/permissionedPools/WrappedPermissionedToken.sol, src/hooks/permissionedPools/WrappedPermissionedTokenFactory.sol, src/hooks/permissionedPools/interfaces/IAllowlistChecker.sol, src/hooks/permissionedPools/interfaces/IWrappedPermissionedTokenFactory.sol, test/hooks/permissionedPools/PermissionedPoolsBase.sol, test/hooks/permissionedPools/WrappedPermissionedToken.t.sol, test/hooks/permissionedPools/WrappedPermissionedTokenFactory.t.sol
This pull request introduces several updates and new features to the permissioned pools functionality, including refactoring existing code, adding new methods, and implementing comprehensive test coverage. The most significant changes include renaming methods for consistency, adding support for token decimals, updating verification logic, and introducing extensive unit tests for both `WrappedPermissionedToken` and `WrappedPermissionedTokenFactory`.
* Renamed `checkAllowList` to `checkAllowlist` in `IAllowlistChecker` and its implementation for naming consistency. (`[[1]](diffhunk://#diff-cf396ff55c3eae958295860a08f467a35f0a3a0fb96a54d0fa163c5b1ecb8758L54-R54)`, `[[2]](diffhunk://#diff-8c320aa170995dcf703394866bd4a12e0775efc0bbc59b93e55f6b0507d9a543L7-R7)`)
* Added a `decimals()` method in …
=> Wrapped token tests

test/hooks/permissionedPools/PermissionedPositionManager.t.sol, test/hooks/permissionedPools/PermissionedV4Router.t.sol
Changes PermissionedV4Router.t.sol and PermissionedPositionManager.t.sol to expect specific errors rather than using vague vm.expectError()
=> expect specific errors in permissioned pools test suite

src/hooks/permissionedPools/PermissionedPositionManager.sol, src/hooks/permissionedPools/WrappedPermissionedToken.sol, src/hooks/permissionedPools/interfaces/IWrappedPermissionedToken.sol, test/hooks/permissionedPools/PermissionedPositionManager.t.sol
This pull request introduces changes to the `PermissionedPositionManager` contract and related files to enhance permission management for token transfers and improve test coverage. Key updates include adding stricter transfer rules, introducing helper methods for permission checks, and expanding test cases to validate the new functionality.
* [`src/hooks/permissionedPools/PermissionedPositionManager.sol`](diffhunk://#diff-85dca6b1a9231c32006abbbffdf0e3e896edc4f1c5bf7fb599f84226cdb0e0d9L39-R58): Enhanced the `transferFrom` method to allow only admins of permissioned tokens to transfer positions containing their tokens. Added `_getOwner` and `_verifiedPermissionedTokenOf` helper methods for permission checks. Introduced new error types `Unauthorized` and `SafeTransferDisabled`. …
=> Permissioned Pools: Transfers by admins

package.json, src/hooks/WstETHHook.sol, src/hooks/WstETHRoutingHook.sol, test/hooks/WstETHHook.fork.t.sol, test/hooks/WstETHHook.t.sol
This pull request introduces enhancements to the `WstETHHook` contract, adds a new `WstETHRoutingHook` for simulation purposes, and updates related tests to ensure compatibility and functionality. Key changes include the addition of virtual modifiers, improved precision in withdrawal calculations, and the introduction of a routing hook for simulating swaps without actual deposits. Test cases have been expanded to validate the new functionality.
- Added the `virtual` modifier to the `_deposit` function to allow overriding in derived contracts.
- Enhanced the `_withdraw` function to improve precision by calculating the actual unwrapped amount using stETH shares and their corresponding pooled ETH.
- Added a new `WstETHRoutingHook` contract to simulate the behavior of `WstETHHook` with the v4 …
=> Add WstETHRoutingHook, fix rounding bug
